### ISSUE TITLE
Calendar entry for sig metadata model management is invalid; date isn't correct

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#350]
```
Traceback (most recent call last):
  File "scripts/calendar_import.py", line 172, in <module>
    fire.Fire(CalendarUpdater)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "scripts/calendar_import.py", line 105, in sync
    day_of_week = datetime.strptime("{} {}".format(date, time_start), '%m/%d/%Y %I:%M%p').strftime('%A').upper()[0:2]
  File "/usr/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '26/5/2020 8:00am' does not match format '%m/%d/%Y %I:%M%p'
```

**Comment by jlewi** [comment]
/assign @karlschriek 

@karlschriek could you please send a PR to fix?

**Comment by jlewi** [comment]
@Swikar @karlschriek Is the time for the meeting correct? Right now it overlaps with the regular community meeting on Tuesdays; was it supposed to alternate with the community meetings?

/cc @aronchick

**Comment by Swikar** [comment]
@jlewi you’re right. It should suppose on Thursday not Tuesday. I will correct date and send PR

**Comment by Swikar** [comment]
@jlewi you’re right. sorry It should suppose on Thursday not Tuesday. I have moved date and new PR
https://github.com/kubeflow/community/pull/352
