### ISSUE TITLE
AttributeError: module 'asyncio' has no attribute 'coroutine'

### ISSUE THREAD

**Issue by maisam94** [kubeflow/community#698]
Hey,
I am using jupyterlab on EKS, used image kubeflownotebookswg/jupyter-tensorflow-cuda-full
After installation, I am  clone the repository from GitHub with authentication.

I get an error:

Traceback (most recent call last): File "/opt/conda/lib/python3.11/site-packages/jupyterlab_git/git.py", line 175, in execute code, output, error = await call_subprocess_with_authentication( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/conda/lib/python3.11/site-packages/jupyterlab_git/git.py", line 119, in call_subprocess_with_authentication i = await p.expect(["Username for .*: ", "Password for .*:"], async_=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/conda/lib/python3.11/site-packages/pexpect/spawnbase.py", line 343, in expect return self.expect_list(compiled_pattern_list, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/conda/lib/python3.11/site-packages/pexpect/spawnbase.py", line 369, in expect_list from ._async import expect_async File "/opt/conda/lib/python3.11/site-packages/pexpect/_async.py", line 7, in <module> @asyncio.coroutine ^^^^^^^^^^^^^^^^^ AttributeError: module 'asyncio' has no attribute 'coroutine'

How can fix it, and can we clone from GitHub? 

Thanks

**Comment by thesuperzapper** [comment]
@maisam94 please do not use the community repo for issues.

Please raise this in the `kubeflow/kubeflow` repo.

/close
